spring.application.name=transaction-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/transaction_db
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Broker AMQP
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.fail-on-unsupported-database=false

# Logging
server.port=8081